### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [spawnfest/spawnfest.github.io#176]
List below, with a minimal description, what you think might be good ideas to see implemented in SpawnFest 2023. We already have [some ideas up](https://spawnfest.org/ideas) (list if being reviewed) but we're sure there's plenty more out there. Remember, the competition is 48h long so the idea should try to adapt to that time frame.

**Comment by paulo-ferraz-oliveira** [comment]
* a statsd client
  * there's https://github.com/klarna/statsd-erlang, from 7 years ago (I recently wanted to use it and ended up forking it - https://github.com/paulo-ferraz-oliveira/statsd-erlang)
  * https://github.com/lpgauth/statsderl, but it doesn't compile well in MacOS (since it relies on a NIF, I believe)

**Comment by hugobarauna** [comment]
**For the Livebook special bracket**

Livebook Apps: a Livebook App is a way to turn a Livebook notebook into an interactive web application. You can build all sorts of different apps, like internal tools, [interactive automation tasks](https://news.livebook.dev/whats-new-in-livebook-0.10---introducing-multi-session-livebook-apps-3Dbpss), [multi-user real-time apps](https://news.livebook.dev/deploy-notebooks-as-apps-quality-of-life-upgrades---launch-week-1---day-1-2OTEWI), [data visualization](https://hugobarauna-livebook.hf.space/apps/github-stars), [machine learning based apps](https://news.livebook.dev/build-and-deploy-a-whisper-chat-app-to-hugging-face-in-15-minutes---launch-week-1---day-4-wYM0w) and more.

**Comment by starbelly** [comment]
- xml library work. Something new or better just improve xmerl (focus on security) Could also improve on saxy too. That's perhaps way too daunting for a 48 hour hackathon though 😄 

- A library to collect socket stats from an operating system (safely).  

- Hot patch framework

- Tasks and streams in erlang. 

- [BBR](https://research.google/pubs/pub45646/) in <insert beam language here> 

- Flow control for erlang distribution per the ability to turn dist busy buffer handling off now.

**Comment by paulo-ferraz-oliveira** [comment]
2023 is done. Will re-open this next year, if necessary. 😄 Thanks for all your contributions.
