### ISSUE TITLE
background video does not play on mobile

### ISSUE THREAD

**Issue by starbelly** [spawnfest/spawnfest.github.io#89]
This issue should be considered of the lowest priority, I simply happened to notice it wasn't working. It probably worked at one point, but then standards changed. There's a lot of reasons it might not work, ranging from css, to video posters, etc. 

If we can we should fix this, but as stated, it's of the lowest priority.

**Comment by starbelly** [comment]
It's not clear where this is an actual issue. the background video is now working 🤷

**Comment by paulo-ferraz-oliveira** [comment]
For me it's not working :)

**Comment by paulo-ferraz-oliveira** [comment]
Waddaya know (?) It started working out of the blue. Cosmic radiation is strong, these days.
